<?php

require_once dirname(__FILE__) . '/../FileData.php';

/**
 * Test class for FileData.
 * Generated by PHPUnit on 2012-01-03 at 13:53:40.
 */
class FileDataTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FileData
	 */
	protected $object;
	protected $object2;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FileData('../weather.dat');
		$this->object2 = new FileData('../football.dat');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	public function testInhaltVorhanden() {
		$this->assertFileExists('../weather.dat');
	}
	
	public function testLineCount()
    {
        $this->assertCount(40, $this->object->getLines());
    }
	
	public function testSmallestTempSpread() {
	   $this->assertEquals(14, $this->object->getSmallestSpread(8, 37, 0, 1, 2));
	}

	public function testGetValue() {
	   $this->assertEquals(90, $this->object->getValue(12, 1));
	}
	
	public function testSmallestGoalSpread() {
	   $this->assertEquals('Sunderland', $this->object2->getSmallestSpread(5, 25, 1, 6, 7));
	}

	
   
}

?>
